// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const Inter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

const Inter = Inter({
  variable: "--font-Inter-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Daybaby - Acompanhe a rotina do seu bebê",
  description: "Monitore mamadas, sonecas e a rotina do seu pequeno com praticidade e carinho",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={{inter.className}>
      >
        {children}
      </body>
    </html>
  );
}
